name: Build Wheels

on: [push] # TODO

env:
    LIBRARY_BASE_REPO: NTIA/p2108
    LIBRARY_RELEASE_TAG: v1.0-rc.1
    LIBRARY_DESTINATION_DIRECTORY: 'src/ITS/ITU/PSeries/P2108/'

jobs:
  build_wheel:
    name: Build a universal, cross-platform wheel
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # Only the binaries required for the current platform are downloaded. Note that the distributed
      # wheel for proplib python packages includes all binaries, so that the wheel is inherently cross-platform.
      - name: Download required ${{ env.LIBRARY_RELEASE_TAG }} Windows binaries
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ env.LIBRARY_BASE_REPO }}
          tag: ${{ env.LIBRARY_RELEASE_TAG }}
          fileName: '*.dll'
          tarBall: false
          zipBall: false
          out-file-path: ${{ env.LIBRARY_DESTINATION_DIRECTORY }}

      - name: Download required ${{ env.LIBRARY_RELEASE_TAG }} Linux binaries
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ env.LIBRARY_BASE_REPO }}
          tag: ${{ env.LIBRARY_RELEASE_TAG }}
          fileName: '*.so'
          tarBall: false
          zipBall: false
          out-file-path: ${{ env.LIBRARY_DESTINATION_DIRECTORY }}

      - name: Download required ${{ env.LIBRARY_RELEASE_TAG }} macOS binaries
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ env.LIBRARY_BASE_REPO }}
          tag: ${{ env.LIBRARY_RELEASE_TAG }}
          fileName: '*.dylib'
          tarBall: false
          zipBall: false
          out-file-path: ${{ env.LIBRARY_DESTINATION_DIRECTORY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build dependencies
        run: pip install hatchling

      - name: Build wheels
        run: hatchling build

      - uses: actions/upload-artifact@v4
        with:
          name: universal-wheel
          path: dist/*.whl
  test_wheel:
    name: Test wheel / ${{ matrix.platform.os-name }}
    needs: build_wheel
    runs-on: ${{ matrix.platform.os-runner }}
    strategy:
      matrix:
        platform:
          - os-name: 'Windows (64-bit)'
            os-runner: 'windows-latest'
            arch-id: 'x64'
            release-file-pattern: '*-x64.dll'
          - os-name: 'Windows (32-bit)'
            os-runner: 'windows-latest'
            arch-id: 'x86'
            release-file-pattern: '*-x86.dll'
          - os-name: 'macOS (intel/x64)'
            os-runner: 'macos-13'
            arch-id: 'x64'
            release-file-pattern: '*.dylib'
          - os-name: 'macOS (apple/arm64)'
            os-runner: 'macos-latest'
            arch-id: 'arm64'
            release-file-pattern: '*.dylib'
          - os-name: 'Linux (Ubuntu)'
            os-runner: 'ubuntu-latest'
            arch-id: 'x64'
            release-file-pattern: '*.so'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download wheel
        id: wheel-download
        uses: actions/download-artifact@v4

      - name: debug list files
        run: ls ${{ steps.wheel-download.outputs.download-path }}/universal-wheel/*

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: ${{ matrix.platform.arch-id }}
          python-version: '>=3.9 <3.14'
          cache: 'pip'

      - name: Install dependencies for testing
        run: python -m pip install .[tests]

      - name: Remove source directory # make sure we are testing the wheel, not the cloned package
        run: rm -r ./src

      - name: debug list files
        run: ls ${{ steps.wheel-download.outputs.download-path }}/*

      - name: Install newly-built wheel (macOS/Linux)
        if: ${{ runner.os != 'Windows'}}
        run: python -m pip install ${{ steps.wheel-download.outputs.download-path }}/universal-wheel/*.whl --force-reinstall

      - name: Install newly-built wheel (Windows)
        if: ${{ runner.os == 'Windows'}}
        run: python -m pip install ${{ steps.wheel-download.outputs.download-path }}\universal-wheel\*.whl --force-reinstall

      - name: Run pytest
        run: pytest --cov-report=term-missing --no-cov-on-fail --cov
